---
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - go mod tidy
builds:
  # the majority of bins
  - id: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{ .CommitDate }}' -X 'main.builtBy=github.com/goreleaser/goreleaser-action'"
archives:
  - name_template: "{{ .ProjectName }}"
    id: binary
    format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  footer: |
    # Installation
    
    Don't panic, this is really simple.
    
    1. (Optional) Switch to Desktop Mode on your Steam Deck.
    2. Use Chrome or Firefox to download `sd-ge-proton-updater` and run it.
    3. Reboot your Steam Deck.
    4. Wait a little while for it to download, verify and extract the latest installation of GE-Proton from the official GitHub repo. Timing highly depends on Internet connection speed.
    
    From then on you should be able to set compatibility in an unsupported game's properties (eg, Divinity Original Sin Enhanced Edition) and it should hopefully work much better!
    
    # How to update GE-Proton
    
    This program will run when your steam deck boots up and automatically grab the latest version of GE-Proton. See README.md for more information.
    
